name: Code Correction 1 Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Installer les dépendances (g++, Catch2)
      - run: sudo apt-get update && sudo apt-get install -y g++

      # Télécharger Catch2 (header-only, pas besoin de compilation)
      - run: wget https://raw.githubusercontent.com/eecs280staff/unit_test_framework/main/unit_test_framework.hpp

      # Compiler et exécuter les tests
      - run: g++ -std=c++11 test.cpp -o test && ./test
